version: '3'
services:
  web:
    command: python trends.py update 0 450
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
    ports:
      - 81:5000
    volumes:
      - ./logs:/code/logs
      - .:/code
