version: '3'
services:
  web:
    command: python trends.py update 0 1400
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
    ports:
      - 81:5000
    volumes:
      - ./logs:/code/logs
      - .:/code
      - /home/anna/proxys.txt:/opt/application/proxys.txt
